services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container-spring
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-library:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test


volumes:
  mongodb-library:
    external: true
# to access -> docker exec -it 273 mongosh "mongodb://user:password@localhost:27017"
