services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container-spring
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
volumes:
  mongodb_data:
# to access -> docker exec -it 273 mongosh "mongodb://user:password@localhost:27017"
